### ISSUE TITLE
Pip installing error in Colab

### ISSUE THREAD

**Issue by AlexRMU** [juancarlospaco/faster-than-requests#104]
Colab
```
!pip install faster_than_requests --log l1.txt

!pip install faster-than-requests --log l2.txt

!wget "https://files.pythonhosted.org/packages/15/7e/b9aee0da461905d5d74e8e34ed5705aa3551abdb32688a8ae25c5ffd1072/faster_than_requests-c66bdc9.zip" -O "faster_than_requests-c66bdc9.zip"
!pip install /content/faster_than_requests-c66bdc9.zip  --log l3.txt
```
```
ERROR: Could not find a version that satisfies the requirement faster_than_requests (from versions: none)
ERROR: No matching distribution found for faster_than_requests

ERROR: Could not find a version that satisfies the requirement faster-than-requests (from versions: none)
ERROR: No matching distribution found for faster-than-requests

Processing ./faster_than_requests-c66bdc9.zip
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
<details>
  <summary>l1.txt</summary>
```
2020-11-16T16:41:28,401 Using pip 20.2.4 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
2020-11-16T16:41:28,403 Non-user install because site-packages writeable
2020-11-16T16:41:28,549 Created temporary directory: /tmp/pip-ephem-wheel-cache-9efdksuv
2020-11-16T16:41:28,550 Created temporary directory: /tmp/pip-req-tracker-07urfr_c
2020-11-16T16:41:28,550 Initialized build tracking at /tmp/pip-req-tracker-07urfr_c
2020-11-16T16:41:28,550 Created build tracker: /tmp/pip-req-tracker-07urfr_c
2020-11-16T16:41:28,550 Entered build tracker: /tmp/pip-req-tracker-07urfr_c
2020-11-16T16:41:28,550 Created temporary directory: /tmp/pip-install-8w16g8sv
2020-11-16T16:41:28,618 1 location(s) to search for versions of faster-than-requests:
2020-11-16T16:41:28,618 * https://pypi.org/simple/faster-than-requests/
2020-11-16T16:41:28,618 Fetching project page and analyzing links: https://pypi.org/simple/faster-than-requests/
2020-11-16T16:41:28,618 Getting page https://pypi.org/simple/faster-than-requests/
2020-11-16T16:41:28,619 Found index url https://pypi.org/simple
2020-11-16T16:41:28,695   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/aa/e3/d3018380bfb1415a1a951fb64ad728b74ef985ba5be5f43648599c3a91bb/faster_than_requests-49d49f0.zip#sha256=3054b89557bbbec8d22b669943f898b5ef71d7c11f287d9e9b71a45b7aaeee7b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:28,695   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/19/85/00e7ffcb14c8a9c7f5b366e21e0da6252b05dc80521231df08586dfdeb8d/faster_than_requests-d4d03a6.zip#sha256=30defae729a4b0a67bd986a0cd0898d943a347a2e3e45759e7b9facb02051679 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:28,696   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/55/32/d77019eac8980d71c96ebbd266f324e753d75815e88414bad431c1a7f69d/faster_than_requests-57c7862.zip#sha256=e9d08cd824ced57b940eb3fec2b3b1c221de86efe5fc575b6b495c283c80116b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:28,696   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:28,696   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/27/28/e9b3fe211789887b0c088efb937f2c48fcfe3bc247aee0138c6f47980c31/faster_than_requests-272d664.zip#sha256=3d7be5ebcc3fa2a52cd2a59918840d43b5a48747f5414a80c85439d3e161b83d (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:28,696   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/ce/97/e900361ad03ec1bea16c029e1d349487d0e619ae53170e3b935a1cd342cc/faster_than_requests-eb38cdb.zip#sha256=900e959cd2552950d5d53b6ca16fb1c72c8ff5aef2cdbadcb7fb1a3ba72c041c (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:28,696   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/15/7e/b9aee0da461905d5d74e8e34ed5705aa3551abdb32688a8ae25c5ffd1072/faster_than_requests-c66bdc9.zip#sha256=bcd79f1903fdaf1c965ab238d281a199fc8a2b4cb1e685e2a395b8dbb9d26616 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:28,697 Given no hashes to check 0 links for project 'faster-than-requests': discarding no candidates
2020-11-16T16:41:28,698 ERROR: Could not find a version that satisfies the requirement faster_than_requests (from versions: none)
2020-11-16T16:41:28,698 ERROR: No matching distribution found for faster_than_requests
2020-11-16T16:41:28,698 Exception information:
2020-11-16T16:41:28,698 Traceback (most recent call last):
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 228, in _main
2020-11-16T16:41:28,698     status = self.run(options, args)
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
2020-11-16T16:41:28,698     return func(self, options, args)
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 324, in run
2020-11-16T16:41:28,698     reqs, check_supported_wheels=not options.target_dir
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
2020-11-16T16:41:28,698     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
2020-11-16T16:41:28,698     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
2020-11-16T16:41:28,698     self._populate_link(req)
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
2020-11-16T16:41:28,698     req.link = self._find_requirement_link(req)
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
2020-11-16T16:41:28,698     best_candidate = self.finder.find_requirement(req, upgrade)
2020-11-16T16:41:28,698   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/index/package_finder.py", line 930, in find_requirement
2020-11-16T16:41:28,698     req)
2020-11-16T16:41:28,698 pip._internal.exceptions.DistributionNotFound: No matching distribution found for faster_than_requests
2020-11-16T16:41:28,699 Removed build tracker: '/tmp/pip-req-tracker-07urfr_c'
```
</details>
<details>
  <summary>l2.txt</summary>
```
2020-11-16T16:41:29,307 Using pip 20.2.4 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
2020-11-16T16:41:29,309 Non-user install because site-packages writeable
2020-11-16T16:41:29,455 Created temporary directory: /tmp/pip-ephem-wheel-cache-8w80pz_h
2020-11-16T16:41:29,456 Created temporary directory: /tmp/pip-req-tracker-lv2w6j9_
2020-11-16T16:41:29,456 Initialized build tracking at /tmp/pip-req-tracker-lv2w6j9_
2020-11-16T16:41:29,456 Created build tracker: /tmp/pip-req-tracker-lv2w6j9_
2020-11-16T16:41:29,456 Entered build tracker: /tmp/pip-req-tracker-lv2w6j9_
2020-11-16T16:41:29,456 Created temporary directory: /tmp/pip-install-aw4g_6oq
2020-11-16T16:41:29,526 1 location(s) to search for versions of faster-than-requests:
2020-11-16T16:41:29,526 * https://pypi.org/simple/faster-than-requests/
2020-11-16T16:41:29,526 Fetching project page and analyzing links: https://pypi.org/simple/faster-than-requests/
2020-11-16T16:41:29,526 Getting page https://pypi.org/simple/faster-than-requests/
2020-11-16T16:41:29,527 Found index url https://pypi.org/simple
2020-11-16T16:41:29,604   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/aa/e3/d3018380bfb1415a1a951fb64ad728b74ef985ba5be5f43648599c3a91bb/faster_than_requests-49d49f0.zip#sha256=3054b89557bbbec8d22b669943f898b5ef71d7c11f287d9e9b71a45b7aaeee7b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:29,604   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/19/85/00e7ffcb14c8a9c7f5b366e21e0da6252b05dc80521231df08586dfdeb8d/faster_than_requests-d4d03a6.zip#sha256=30defae729a4b0a67bd986a0cd0898d943a347a2e3e45759e7b9facb02051679 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:29,604   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/55/32/d77019eac8980d71c96ebbd266f324e753d75815e88414bad431c1a7f69d/faster_than_requests-57c7862.zip#sha256=e9d08cd824ced57b940eb3fec2b3b1c221de86efe5fc575b6b495c283c80116b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:29,605   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:29,605   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/27/28/e9b3fe211789887b0c088efb937f2c48fcfe3bc247aee0138c6f47980c31/faster_than_requests-272d664.zip#sha256=3d7be5ebcc3fa2a52cd2a59918840d43b5a48747f5414a80c85439d3e161b83d (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:29,605   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/ce/97/e900361ad03ec1bea16c029e1d349487d0e619ae53170e3b935a1cd342cc/faster_than_requests-eb38cdb.zip#sha256=900e959cd2552950d5d53b6ca16fb1c72c8ff5aef2cdbadcb7fb1a3ba72c041c (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:29,605   Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/15/7e/b9aee0da461905d5d74e8e34ed5705aa3551abdb32688a8ae25c5ffd1072/faster_than_requests-c66bdc9.zip#sha256=bcd79f1903fdaf1c965ab238d281a199fc8a2b4cb1e685e2a395b8dbb9d26616 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
2020-11-16T16:41:29,606 Given no hashes to check 0 links for project 'faster-than-requests': discarding no candidates
2020-11-16T16:41:29,606 ERROR: Could not find a version that satisfies the requirement faster-than-requests (from versions: none)
2020-11-16T16:41:29,607 ERROR: No matching distribution found for faster-than-requests
2020-11-16T16:41:29,607 Exception information:
2020-11-16T16:41:29,607 Traceback (most recent call last):
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 228, in _main
2020-11-16T16:41:29,607     status = self.run(options, args)
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
2020-11-16T16:41:29,607     return func(self, options, args)
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 324, in run
2020-11-16T16:41:29,607     reqs, check_supported_wheels=not options.target_dir
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
2020-11-16T16:41:29,607     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
2020-11-16T16:41:29,607     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
2020-11-16T16:41:29,607     self._populate_link(req)
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
2020-11-16T16:41:29,607     req.link = self._find_requirement_link(req)
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
2020-11-16T16:41:29,607     best_candidate = self.finder.find_requirement(req, upgrade)
2020-11-16T16:41:29,607   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/index/package_finder.py", line 930, in find_requirement
2020-11-16T16:41:29,607     req)
2020-11-16T16:41:29,607 pip._internal.exceptions.DistributionNotFound: No matching distribution found for faster-than-requests
2020-11-16T16:41:29,608 Removed build tracker: '/tmp/pip-req-tracker-lv2w6j9_'
```
</details>
<details>
  <summary>l3.txt</summary>
```
2020-11-16T16:41:33,844 Using pip 20.2.4 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
2020-11-16T16:41:33,846 Non-user install because site-packages writeable
2020-11-16T16:41:33,994 Created temporary directory: /tmp/pip-ephem-wheel-cache-2vm3gxy1
2020-11-16T16:41:33,995 Created temporary directory: /tmp/pip-req-tracker-ktwml60r
2020-11-16T16:41:33,995 Initialized build tracking at /tmp/pip-req-tracker-ktwml60r
2020-11-16T16:41:33,995 Created build tracker: /tmp/pip-req-tracker-ktwml60r
2020-11-16T16:41:33,995 Entered build tracker: /tmp/pip-req-tracker-ktwml60r
2020-11-16T16:41:33,996 Created temporary directory: /tmp/pip-install-zoicuzkr
2020-11-16T16:41:33,999 Processing ./faster_than_requests-c66bdc9.zip
2020-11-16T16:41:33,999   Created temporary directory: /tmp/pip-req-build-tcjrb0t_
2020-11-16T16:41:34,097   Added file:///content/faster_than_requests-c66bdc9.zip to build tracker '/tmp/pip-req-tracker-ktwml60r'
2020-11-16T16:41:34,097     Running setup.py (path:/tmp/pip-req-build-tcjrb0t_/setup.py) egg_info for package from file:///content/faster_than_requests-c66bdc9.zip
2020-11-16T16:41:34,097     Created temporary directory: /tmp/pip-pip-egg-info-mogmvj9_
2020-11-16T16:41:34,098     Running command python setup.py egg_info
2020-11-16T16:41:34,420     Traceback (most recent call last):
2020-11-16T16:41:34,420       File "<string>", line 1, in <module>
2020-11-16T16:41:34,420       File "/tmp/pip-req-build-tcjrb0t_/setup.py", line 1, in <module>
2020-11-16T16:41:34,421         import os, sys, pathlib, setuptools, sysconfig, platform, importlib.metadata, atexit
2020-11-16T16:41:34,421     ModuleNotFoundError: No module named 'importlib.metadata'
2020-11-16T16:41:34,440 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-11-16T16:41:34,440 Exception information:
2020-11-16T16:41:34,440 Traceback (most recent call last):
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 228, in _main
2020-11-16T16:41:34,440     status = self.run(options, args)
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
2020-11-16T16:41:34,440     return func(self, options, args)
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 324, in run
2020-11-16T16:41:34,440     reqs, check_supported_wheels=not options.target_dir
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
2020-11-16T16:41:34,440     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
2020-11-16T16:41:34,440     abstract_dist = self._get_abstract_dist_for(req_to_install)
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
2020-11-16T16:41:34,440     abstract_dist = self.preparer.prepare_linked_requirement(req)
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 483, in prepare_linked_requirement
2020-11-16T16:41:34,440     req, self.req_tracker, self.finder, self.build_isolation,
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
2020-11-16T16:41:34,440     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
2020-11-16T16:41:34,440     self.req.prepare_metadata()
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
2020-11-16T16:41:34,440     self.metadata_directory = self._generate_metadata()
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
2020-11-16T16:41:34,440     details=self.name or "from {}".format(self.link)
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/build/metadata_legacy.py", line 73, in generate_metadata
2020-11-16T16:41:34,440     command_desc='python setup.py egg_info',
2020-11-16T16:41:34,440   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
2020-11-16T16:41:34,440     raise InstallationError(exc_msg)
2020-11-16T16:41:34,440 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-11-16T16:41:34,442 Removed file:///content/faster_than_requests-c66bdc9.zip from build tracker '/tmp/pip-req-tracker-ktwml60r'
2020-11-16T16:41:34,442 Removed build tracker: '/tmp/pip-req-tracker-ktwml60r'
```
</details>

**Comment by juancarlospaco** [comment]
We use Rolling Release, the version is just the Git commit short hash. 

`sudo pip3 install faster-than-requests==57c7862 --no-binary :all: `

**Comment by AlexRMU** [comment]
```
ERROR: Could not find a version that satisfies the requirement faster-than-requests==57c7862 (from versions: none)
ERROR: No matching distribution found for faster-than-requests==57c7862
```

**Comment by juancarlospaco** [comment]
You must have PIP version `20.2.4` or higher.

Or try another git commit hash like
`sudo pip3 install faster-than-requests==c66bdc9 --no-binary :all: `

**Comment by AlexRMU** [comment]
pip 20.2.4
I couldn't even install it directly from the archive (see l3 log)

**Comment by AlexRMU** [comment]
[l3.txt](https://github.com/juancarlospaco/faster-than-requests/files/5551744/l3.txt) or https://pastebin.com/raw/0uqdeS21
`ModuleNotFoundError: No module named 'importlib.metadata'`
importlib-metadata is 2.0.0
The Internet says that this may be due to the Python version being too large (3.6.9)

**Comment by AlexRMU** [comment]
I can try pipenv or update Python

**Comment by AlexRMU** [comment]
https://github.com/juancarlospaco/faster-than-requests/blob/86f59b7295b27725e3aa5c9ff7aff40cfb3b8097/PKG-INFO#L41
Requires-Python: >=3.8

**Comment by AlexRMU** [comment]
`!python3.9 -m pip install faster_than_requests`
I installed 3.9 and it worked

**Comment by AlexRMU** [comment]
Installing Python 3.9 on Colab
```
!apt install build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev python3-tk

!wget https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz

!tar xzf Python-3.9.0.tgz

%cd Python-3.9.0
!./configure --enable-optimizations
!make altinstall
```
