### ISSUE TITLE
pip install can't find a version that satisfies the requirement faster_than_requests

### ISSUE THREAD

**Issue by Thuliumify** [juancarlospaco/faster-than-requests#134]
C:\Users\User>pip install faster_than_requests
ERROR: Could not find a version that satisfies the requirement faster_than_requests
ERROR: No matching distribution found for faster_than_requests

Is the package taken out of PyPi?

**Comment by juancarlospaco** [comment]
Nope, we do not deleted the package from PyPI.
- https://pypi.org/project/faster-than-requests/#history

:shrug:

**Comment by Art-em1s** [comment]
Same issue
![image](https://user-images.githubusercontent.com/7710411/107876277-01065a80-6ebd-11eb-94f6-343f82251948.png)

**Comment by juancarlospaco** [comment]
I can not fix PIP bugs, but maybe just try using the source code instead...

Assuming you already have Windows 64Bit and CPython 3.9 64Bit:

- https://gitforwindows.org (Not really mandatory, but useful, so you dont have to download files by hand)
- You MUST reboot the PC after installing Git.

![windows-compile](https://user-images.githubusercontent.com/1189414/107665391-26e8f080-6c6c-11eb-9fa1-742265c1d57b.png)

Commands in order to copy & paste:
- `pip install pip --upgrade`  (Not really mandatory, but good practice)
- `pip install choosenim_install`
- `pip install nimble_install --install-option="--nimble=nimpy"`
- `git clone https://github.com/juancarlospaco/faster-than-requests.git`
- `cd faster-than-requests`
- `cd src`
- `nim c -d:ssl -d:danger --gc:arc --app:lib --out:faster_than_requests.pyd faster_than_requests.nim`
- Copy `faster_than_requests.pyd` on the same folder as the `.py` file that should import it, it is ready for use.

**Comment by Thuliumify** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-req-build-qdjt_0rm\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-req-build-qdjt_0rm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-ay10qh91'
         cwd: C:\Users\User\AppData\Local\Temp\pip-req-build-qdjt_0rm\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-req-build-qdjt_0rm\setup.py", line 1, in <module>
        import os, sys, pathlib, setuptools, sysconfig, platform, importlib.metadata, atexit
    ModuleNotFoundError: No module named 'importlib.metadata'
    
    I tried installing importlib externally but I found no luck in that

**Comment by Itamai** [comment]
I get this issue when using pip is this really a bug from pip?
command: `python -m pip install faster-than-requests`
```
Collecting faster-than-requests
  Using cached faster_than_requests-3572925.zip (1.7 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8). Requested faster-than-requests from https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 has inconsistent version: filename has '3572925', but metadata has '20.10.19'
ERROR: Could not find a version that satisfies the requirement faster-than-requests
ERROR: No matching distribution found for faster-than-requests
```

**Comment by juancarlospaco** [comment]
Please try installing the latest version:

- https://pypi.org/project/faster-than-requests/21.03.03/#files

Older versions may fail due to undocumented changes on PIP/PyPI/etc.
That should work correctly. Sorry for the delay. :slightly_smiling_face:

**Comment by GergelyMolnar** [comment]
Hi @juancarlospaco, 

Thanks for the hard work making this tool awesome. 

I'd just like to add some input. I'm using a very different system than the OP but I couldn't install your package.

```bash
$ uname -a 
Linux gary-dt 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I've tried to install the package on fresh venv for Python 3.6, 3.7 and 3.8. No luck.

This output is from installing to Python 3.7
```bash
$ pip install -r requirements.txt
Collecting faster-than-requests==21.03.03
  Using cached faster_than_requests-21.03.03.zip (4.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/xyz/PycharmProjects/qwerty_api_fetch/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fc1tl_1_/faster-than-requests_8b7c58fbeabb40fbafc85e8347124092/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fc1tl_1_/faster-than-requests_8b7c58fbeabb40fbafc85e8347124092/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uwsfgwcz
         cwd: /tmp/pip-install-fc1tl_1_/faster-than-requests_8b7c58fbeabb40fbafc85e8347124092/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/xyz/PycharmProjects/qwerty_api_fetch/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-zwml6kyx/choosenim-install_ea5312a8528048d796dc9ed8749862d0/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-zwml6kyx/choosenim-install_ea5312a8528048d796dc9ed8749862d0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-s2elzjhu
           cwd: /tmp/pip-wheel-zwml6kyx/choosenim-install_ea5312a8528048d796dc9ed8749862d0/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for choosenim-install
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/xyz/PycharmProjects/qwerty_api_fetch/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpwgbbkbzg', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fc1tl_1_/faster-than-requests_8b7c58fbeabb40fbafc85e8347124092/setup.py", line 2, in <module>
        setuptools.setup(package_data = {"": ["*.nim", "*.nims", "*.cfg", "*.dll", "*.so", "*.h", "*.hpp"]})
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/setuptools/dist.py", line 689, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
        replace_conflicting=replace_conflictings
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/xyz/PycharmProjects/qwerty_api_fetch/venv/lib/python3.7/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/xyz/PycharmProjects/qwerty_api_fetch/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpwgbbkbzg', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip#sha256=3cc247556e10c64d8897933304670c873236026b4ef9f219215b124e990c2dac (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faster-than-requests==21.03.03
ERROR: No matching distribution found for faster-than-requests==21.03.03
```

Cheers

**Comment by juancarlospaco** [comment]
Yeah, PIP/Pypi seems kinda buggy, the file is there https://pypi.org/project/faster-than-requests/21.03.03/#files

Try installing/updating the `wheel` python package (we do not need it, but it seems PIP does).

Do it from command line terminal window, not from inside IDE.

- Use `pip install faster-than-requests==21.03.03 --no-binary :all:`
