### ISSUE TITLE
After installing from source can't import in python

### ISSUE THREAD

**Issue by zabir-nabil** [juancarlospaco/faster-than-requests#139]
First of all, it seems the pip wheels are broken.

I am using ubuntu 20.04, python 3.8

So, I tried installing from source and it seems everything succeded after a few trial and error but still can't import it:

```
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests$ cd src
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ nimble install nimpy
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
Downloading https://github.com/yglukhov/nimpy using git
  Verifying dependencies for nimpy@0.1.1
 Installing nimpy@0.1.1
   Success: nimpy installed successfully.
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
/home/vmuser/Data/faster-than-requests/src/faster_than_requests.nim.cfg(11, 3) Error: 'none', 'boehm' or 'refc' expected, but 'orc' found
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ nim --version
Nim Compiler Version 1.0.6 [Linux: amd64]
Compiled at 2020-02-27
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ curl https://nim-lang.org/choosenim/init.sh -sSf | sh
choosenim-init: Downloading choosenim-0.7.4_linux_amd64
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
y
    Answer: Downloading Nim 1.4.2 from nim-lang.org
[#                                                 ] 0mb 0kb/s
      Info: Binary build unavailable, building from source
[##################################################] 100.0% 0kb/s
 Extracting nim-1.4.2.tar.xz
   Building Nim 1.4.2
   Building koch
   Building Nim
   Building tools (nimble, nimgrep, nimpretty, nimsuggest, testament)
  Installed component 'nim'
   Warning: Binary 'nim' is shadowed by '/usr/bin/nim'.
      Hint: Ensure that '/home/vmuser/.nimble/bin' is before '/usr/bin' in the PATH env var.
  Installed component 'nimble'
   Warning: Binary 'nimble' is shadowed by '/usr/bin/nimble'.
  Installed component 'nimgrep'
   Warning: Binary 'nimgrep' is shadowed by '/usr/bin/nimgrep'.
  Installed component 'nimpretty'
  Installed component 'nimsuggest'
   Warning: Binary 'nimsuggest' is shadowed by '/usr/bin/nimsuggest'.
  Installed component 'testament'
  Installed component 'nim-gdb'
   Switched to Nim 1.4.2
choosenim-init: ChooseNim installed in /home/vmuser/.nimble/bin
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.
choosenim-init: Place the following line in the ~/.profile or ~/.bashrc file.
choosenim-init:     export PATH=/home/vmuser/.nimble/bin:$PATH
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ nim --version
Nim Compiler Version 1.0.6 [Linux: amd64]
Compiled at 2020-02-27
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ export PATH=/home/vmuser/.nimble/bin:$PATH
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ source
-bash: source: filename argument required
source: usage: source filename [arguments]
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ source ~/.bashrc
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$ nim --version
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2021-02-18
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$ nim c -d:ssl --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
Hint: used config file '/home/vmuser/.choosenim/toolchains/nim-1.4.2/config/nim.cfg' [Conf]
Hint: used config file '/home/vmuser/.choosenim/toolchains/nim-1.4.2/config/config.nims' [Conf]
Hint: used config file '/home/vmuser/Data/faster-than-requests/src/faster_than_requests.nim.cfg' [Conf]
..........................................................................
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/httpcore.nim(154, 25) Hint: passing 'headers.table[toCaseInsensitive(headers, key)]' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(121, 40) template/generic instantiation of `exportpy` from here
/home/vmuser/.nimble/pkgs/nimpy-0.1.1/nimpy.nim(1053, 32) Warning: Cannot prove that 'arg0timeout' is initialized. This will become a compile time error in the future. [ProveInit]
faster_than_requests.nim(138, 16) Hint: passing 'u[].scheme' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 28) Hint: passing 'u[].username' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 42) Hint: passing 'u[].password' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 56) Hint: passing 'u[].hostname' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 70) Hint: passing 'u[].port' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 80) Hint: passing 'u[].path' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 90) Hint: passing 'u[].query' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 101) Hint: passing 'u[].anchor' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/httpclient.nim(1074, 46) Hint: passing 'resp.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/httpclient.nim(1165, 46) Hint: passing 'resp.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/collections/sequtils.nim(203, 18) Hint: passing 'prev' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/collections/sequtils.nim(207, 22) Hint: passing 'prev' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(391, 23) Hint: passing 'href' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(392, 25) Hint: passing 'href' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1884, 34) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1887, 39) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1896, 32) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1975, 37) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/asyncdispatch.nim(1287, 39) Hint: passing 'adata.readList' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_formatfloat.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_parseutils.nim
CC: stdlib_math.nim
CC: stdlib_unicode.nim
CC: stdlib_strutils.nim
CC: stdlib_pathnorm.nim
CC: stdlib_options.nim
CC: stdlib_times.nim
CC: stdlib_os.nim
CC: stdlib_hashes.nim
CC: stdlib_tables.nim
CC: stdlib_heapqueue.nim
CC: stdlib_deques.nim
CC: stdlib_asyncfutures.nim
CC: stdlib_asyncstreams.nim
CC: stdlib_monotimes.nim
CC: stdlib_nativesockets.nim
CC: stdlib_sets.nim
CC: stdlib_dynlib.nim
CC: stdlib_openssl.nim
CC: stdlib_net.nim
CC: stdlib_selectors.nim
CC: stdlib_asyncdispatch.nim
CC: stdlib_sqlite3.nim
CC: stdlib_db_common.nim
CC: stdlib_db_sqlite.nim
CC: stdlib_streams.nim
CC: stdlib_lexbase.nim
CC: stdlib_parsexml.nim
CC: stdlib_strtabs.nim
CC: stdlib_xmltree.nim
CC: stdlib_htmlparser.nim
CC: stdlib_base64.nim
CC: stdlib_uri.nim
CC: stdlib_random.nim
CC: stdlib_httpcore.nim
CC: stdlib_asyncnet.nim
CC: stdlib_asyncfile.nim
CC: stdlib_httpclient.nim
CC: stdlib_parsejson.nim
CC: stdlib_json.nim
CC: stdlib_sequtils.nim
CC: ../../../.nimble/pkgs/nimpy-0.1.1/nimpy/py_lib.nim
CC: ../../../.nimble/pkgs/nimpy-0.1.1/nimpy/py_utils.nim
CC: ../../../.nimble/pkgs/nimpy-0.1.1/nimpy.nim
CC: stdlib_pegs.nim
CC: stdlib_pcre.nim
CC: stdlib_rtarrays.nim
CC: stdlib_re.nim
CC: stdlib_cpuinfo.nim
CC: stdlib_cpuload.nim
CC: stdlib_locks.nim
CC: stdlib_threadpool.nim
CC: stdlib_strformat.nim
CC: ws.nim
CC: faster_than_requests.nim
Hint:  [Link]
Hint: 130843 lines; 6.543s; 225.074MiB peakmem; Dangerous Release build; proj: faster_than_requests; out: faster_than_requests.pyd [SuccessX]
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faster_than_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faster_than_requests'
>>>
[1]+  Stopped                 python
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$ faster_than_requests
-bash: faster_than_requests: command not found
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$ python3
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
[2]+  Stopped                 python3
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$ conda activate darknet_fastapi
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ nimble install nimpy
Downloading https://github.com/yglukhov/nimpy using git
  Verifying dependencies for nimpy@0.1.1
 Installing nimpy@0.1.1
    Prompt: nimpy@0.1.1 already exists. Overwrite? [y/N]
    Answer: y
   Success: nimpy installed successfully.
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
Hint: used config file '/home/vmuser/.choosenim/toolchains/nim-1.4.2/config/nim.cfg' [Conf]
Hint: used config file '/home/vmuser/.choosenim/toolchains/nim-1.4.2/config/config.nims' [Conf]
Hint: used config file '/home/vmuser/Data/faster-than-requests/src/faster_than_requests.nim.cfg' [Conf]
..........................................................................
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/httpcore.nim(154, 25) Hint: passing 'headers.table[toCaseInsensitive(headers, key)]' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 47) Hint: passing 'respons.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(26, 63) Hint: passing 'respons.version' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(121, 40) template/generic instantiation of `exportpy` from here
/home/vmuser/.nimble/pkgs/nimpy-0.1.1/nimpy.nim(1053, 32) Warning: Cannot prove that 'arg0timeout' is initialized. This will become a compile time error in the future. [ProveInit]
faster_than_requests.nim(138, 16) Hint: passing 'u[].scheme' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 28) Hint: passing 'u[].username' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 42) Hint: passing 'u[].password' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 56) Hint: passing 'u[].hostname' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 70) Hint: passing 'u[].port' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 80) Hint: passing 'u[].path' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 90) Hint: passing 'u[].query' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(138, 101) Hint: passing 'u[].anchor' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/httpclient.nim(1074, 46) Hint: passing 'resp.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/httpclient.nim(1165, 46) Hint: passing 'resp.status' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/collections/sequtils.nim(203, 18) Hint: passing 'prev' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/collections/sequtils.nim(207, 22) Hint: passing 'prev' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(391, 23) Hint: passing 'href' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
faster_than_requests.nim(392, 25) Hint: passing 'href' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1884, 34) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1887, 39) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1896, 32) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/pegs.nim(1975, 37) Hint: passing 'p.tok.literal' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
/home/vmuser/.choosenim/toolchains/nim-1.4.2/lib/pure/asyncdispatch.nim(1287, 39) Hint: passing 'adata.readList' to a sink parameter introduces an implicit copy; if possible, rearrange your program's control flow to prevent it [Performance]
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_formatfloat.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_parseutils.nim
CC: stdlib_math.nim
CC: stdlib_unicode.nim
CC: stdlib_strutils.nim
CC: stdlib_pathnorm.nim
CC: stdlib_options.nim
CC: stdlib_times.nim
CC: stdlib_os.nim
CC: stdlib_hashes.nim
CC: stdlib_tables.nim
CC: stdlib_heapqueue.nim
CC: stdlib_deques.nim
CC: stdlib_asyncfutures.nim
CC: stdlib_asyncstreams.nim
CC: stdlib_monotimes.nim
CC: stdlib_nativesockets.nim
CC: stdlib_sets.nim
CC: stdlib_dynlib.nim
CC: stdlib_openssl.nim
CC: stdlib_net.nim
CC: stdlib_selectors.nim
CC: stdlib_asyncdispatch.nim
CC: stdlib_sqlite3.nim
CC: stdlib_db_common.nim
CC: stdlib_db_sqlite.nim
CC: stdlib_streams.nim
CC: stdlib_lexbase.nim
CC: stdlib_parsexml.nim
CC: stdlib_strtabs.nim
CC: stdlib_xmltree.nim
CC: stdlib_htmlparser.nim
CC: stdlib_base64.nim
CC: stdlib_uri.nim
CC: stdlib_random.nim
CC: stdlib_httpcore.nim
CC: stdlib_asyncnet.nim
CC: stdlib_asyncfile.nim
CC: stdlib_httpclient.nim
CC: stdlib_parsejson.nim
CC: stdlib_json.nim
CC: stdlib_sequtils.nim
CC: ../../../.nimble/pkgs/nimpy-0.1.1/nimpy/py_lib.nim
CC: ../../../.nimble/pkgs/nimpy-0.1.1/nimpy/py_utils.nim
CC: ../../../.nimble/pkgs/nimpy-0.1.1/nimpy.nim
CC: stdlib_pegs.nim
CC: stdlib_pcre.nim
CC: stdlib_rtarrays.nim
CC: stdlib_re.nim
CC: stdlib_cpuinfo.nim
CC: stdlib_cpuload.nim
CC: stdlib_locks.nim
CC: stdlib_threadpool.nim
CC: stdlib_strformat.nim
CC: ws.nim
CC: faster_than_requests.nim
Hint:  [Link]
Hint: 130843 lines; 13.337s; 223.855MiB peakmem; Dangerous Release build; proj: faster_than_requests; out: faster_than_requests.pyd [SuccessX]
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ python
Python 3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faster_than_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faster_than_requests'
>>>
[3]+  Stopped                 python
(darknet_fastapi) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src
$ source ~/.bashrc
(base) vmuser@tigerit-SYS-1029GQ-TVRT:~/Data/faster-than-requests/src$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faster_than_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'faster_than_requests'

```

**Comment by zabir-nabil** [comment]
If I try installing with pip, I get this error:

```
ERROR: Requested faster_than_requests from https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 has different version in metadata: '20.10.19'
```

**Comment by juancarlospaco** [comment]
Please try installing the latest version:

- https://pypi.org/project/faster-than-requests/21.03.03/#files

Older versions may fail due to undocumented changes on PIP/PyPI/etc.
That should work correctly. Sorry for the delay. :slightly_smiling_face:
