### ISSUE TITLE
can't import after installing: FileNotFoundError: [Errno 2] No such file or directory: 'faster_than_requests.nim'

### ISSUE THREAD

**Issue by solder-fumes-asthma** [juancarlospaco/faster-than-requests#145]
Hello, I cant import after installing faster_than_requests. Im running a Pop!_OS 20.10 x64.

I had some issues with installation at first, so the steps that worked for me were the following:
```
$ sudo apt install nim
$ pip3 install faster-than-requests==21.03.03
```
After getting this error for the first time, I also tried installing via downloading the ZIP [here](https://pypi.org/project/faster-than-requests/21.03.03/#files) and then doing:
`$ python3 -m pip install ~/Downloads/faster_than_requests-21.03.03.zip`

I still can't import inside the interpreter. The full error I get is the following:
```
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faster_than_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pablo/.local/lib/python3.8/site-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/home/pablo/.local/lib/python3.8/site-packages/nimporter.py", line 1150, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "/home/pablo/.local/lib/python3.8/site-packages/nimporter.py", line 828, in import_nim_code
    NimCompiler.compile_nim_code(
  File "/home/pablo/.local/lib/python3.8/site-packages/nimporter.py", line 588, in compile_nim_code
    raise NimCompileException(errors[0])
  File "/home/pablo/.local/lib/python3.8/site-packages/nimporter.py", line 56, in __init__
    with open(nim_module, 'r') as mod:
FileNotFoundError: [Errno 2] No such file or directory: 'faster_than_requests.nim'
```

Any help would be appreciated. Pre-thanks!

**Comment by juancarlospaco** [comment]
You need Nim `1.4.6`, `apt` usually has very old versions.
You need CPython `3.9`.
Run the commands in the Bash terminal window, not inside an IDE.

**Comment by juancarlospaco** [comment]
Assuming user made it work (?), with provided comments...
