### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by coder-in-daegu** [juancarlospaco/faster-than-requests#153]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.
C:\Users\USER>pip install faster_than_requests --isolated --disable-pip-version-check --no-cache-dir --no-binary :all:
Collecting faster_than_requests
  Downloading faster_than_requests-3572925.zip (1.7 MB)
     |████████████████████████████████| 1.7 MB 2.2 MB/s
WARNING: Discarding https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8). Requested faster_than_requests from https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 has inconsistent version: filename has '3572925', but metadata has '20.10.19'
  Downloading faster_than_requests-21.03.03.zip (4.9 MB)
     |████████████████████████████████| 4.9 MB 6.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-uia1u0xt\\faster-than-requests_ccb236eb7be947b5a56ce06c26cab79d\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-uia1u0xt\\faster-than-requests_ccb236eb7be947b5a56ce06c26cab79d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-wrw5lhq5'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-uia1u0xt\faster-than-requests_ccb236eb7be947b5a56ce06c26cab79d\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\user\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-wheel-8x3h3eqf\\choosenim-install_1d79b6ae2ceb4feca451b686461acd25\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-wheel-8x3h3eqf\\choosenim-install_1d79b6ae2ceb4feca451b686461acd25\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USER\AppData\Local\Temp\pip-wheel-jzod2csb'
           cwd: C:\Users\USER\AppData\Local\Temp\pip-wheel-8x3h3eqf\choosenim-install_1d79b6ae2ceb4feca451b686461acd25\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for choosenim-install
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\user\appdata\local\programs\python\python38\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\user\\appdata\\local\\programs\\python\\python38\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmp96ooc5pl', '--quiet', 'choosenim_install']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-uia1u0xt\faster-than-requests_ccb236eb7be947b5a56ce06c26cab79d\setup.py", line 2, in <module>
        setuptools.setup(package_data = {"": ["*.nim", "*.nims", "*.cfg", "*.dll", "*.so", "*.h", "*.hpp"]})
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
        return installer(requirement)
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\user\\appdata\\local\\programs\\python\\python38\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmp96ooc5pl', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip#sha256=3cc247556e10c64d8897933304670c873236026b4ef9f219215b124e990c2dac (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading faster_than_requests-21.03.02.zip (3.5 kB)

**Comment by coder-in-daegu** [comment]
fixe
