### ISSUE TITLE
pip issue? 2

### ISSUE THREAD

**Issue by coder-in-daegu** [juancarlospaco/faster-than-requests#155]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

Traceback (most recent call last):
  File "C:\Mixas\config\mixas_window\python\vend\BOT\index.py", line 7, in <module>
    import faster_than_requests
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nimporter.py", line 1150, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nimporter.py", line 828, in import_nim_code
    NimCompiler.compile_nim_code(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nimporter.py", line 558, in compile_nim_code
    cls.ensure_nimpy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nimporter.py", line 270, in ensure_nimpy
    out, errors, _, _ = cls.invoke_compiler('nimble path nimpy'.split())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nimporter.py", line 245, in invoke_compiler
    process = subprocess.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

**Comment by juancarlospaco** [comment]
I only understand English and Spanish.
But again if you have problems just Git clone and compile.
:slightly_smiling_face:

**Comment by juancarlospaco** [comment]
I only understand English and Spanish, sorry.
