### ISSUE TITLE
Import Error [IndexError: list index out of range]

### ISSUE THREAD

**Issue by Switch1024** [juancarlospaco/faster-than-requests#156]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

Full error : 
>>> import faster_than_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user1337\AppData\Roaming\Python\user1337\site-packages\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "C:\Users\user1337\AppData\Roaming\Python\Python39\site-packages\nimporter.py", line 1150, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "C:\Users\user1337\AppData\Roaming\Python\Python39\site-packages\nimporter.py", line 828, in import_nim_code
    NimCompiler.compile_nim_code(
  File "C:\Users\user1337\AppData\Roaming\Python\Python39\site-packages\nimporter.py", line 588, in compile_nim_code
    raise NimCompileException(errors[0])
  File "C:\Users\user1337\AppData\Roaming\Python\Python39\site-packages\nimporter.py", line 48, in __init__
    nim_module = nim_module.splitlines()[-1]
IndexError: list index out of range

**Comment by DavidGoedicke** [comment]
Have the same error on MacOS

regular installation through pip and installation of CPython and him through brew.

**Comment by p-i-** [comment]
Bumping into exactly the same issue.
I'm on a FRESH python 3.95 on macOS.

I'm using `poetry` package manager:
```
brew install python
brew install nim
pip3 install poetry
poetry new
poetry add faster_than_requests
poetry run faster.py
```
And faster.py is the testcase:
```
import faster_than_requests as requests
requests.post('https://httpbin.org/post')
```

Could the author possibly check releases on macOS?
A lot of devs using this platform...

**Comment by p-i-** [comment]
It's actually misreporting due to a bug in `nimporter`'s `NimCompileException` class.
Placing a breakpoint shows the actual error:

```
Error: execution of an external program failed:
'clang
-shared
-o
/Users/pi/Library/Caches/pypoetry/virtualenvs/phoenix-03hFm4CN-py3.9/lib/python3.9/site-packages/faster_than_requests/__pycache__/faster_than_requests.so
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_assertions.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_dollars.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_locks.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_sharedlist.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_formatfloat.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_io.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_system.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_parseutils.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_math.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_unicode.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_strutils.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_pathnorm.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_posix.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_options.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_times.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_os.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_hashes.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_tables.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_heapqueue.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_deques.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_asyncfutures.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_asyncstreams.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_monotimes.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_nativesockets.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_sets.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_dynlib.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_openssl.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_net.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_kqueue.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_selectors.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_asyncdispatch.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_sqlite3.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_db_common.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_db_sqlite.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_streams.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_lexbase.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_parsexml.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_strtabs.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_xmltree.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_htmlparser.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_base64.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_uri.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_random.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_httpcore.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_asyncnet.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_asyncfile.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_httpclient.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_parsejson.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_json.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/@m..@s..@s..@s..@s..@s..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.1@snimpy@spy_types.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_sequtils.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/@m..@s..@s..@s..@s..@s..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.1@snimpy@spy_lib.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/@m..@s..@s..@s..@s..@s..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.1@snimpy@spy_utils.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/@m..@s..@s..@s..@s..@s..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.1@snimpy.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_pegs.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_pcre.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_rtarrays.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_re.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_cpuinfo.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_cpuload.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_threadpool.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/stdlib_strformat.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/@mws.nim.c.o
/Users/pi/.cache/nim/faster_than_requests_r/@mfaster_than_requests.nim.c.o
-lm
-ldl
-fuse-ld=lld
-flto
-s'
```

So maybe the challenge is get that to work from the commandline.

**Comment by p-i-** [comment]
Digging some more, this is the shell build command that is executed:
```
nim c --opt:speed --parallelBuild:0 --gc:refc --threads:on --app:lib -d:release -d:strip  -d:lto -d:ssl --forceBuild:on --os:macos --out:/Users/pi/Library/Caches/pypoetry/virtualenvs/phoenix-03hFm4CN-py3.9/lib/python3.9/site-packages/faster_than_requests/__pycache__/faster_than_requests.so /Users/pi/Library/Caches/pypoetry/virtualenvs/phoenix-03hFm4CN-py3.9/lib/python3.9/site-packages/faster_than_requests/faster_than_requests.nim
```

If I run this from the CLI I get the fail.
Removing `-d:lto`, it works!

So this line needs to be commented out: https://github.com/juancarlospaco/faster-than-requests/blob/master/faster_than_requests/faster_than_requests.nim.cfg#L7
```
-d:ssl
# -d:lto  <-- this is causing the fail on macOS
-d:strip
-d:danger
-d:release
-d:noSignalHandler
-d:nimBinaryStdFiles
-d:nimDisableCertificateValidation
```

The nim guys say `lto` is broken on macos pending fix: https://github.com/nim-lang/Nim/pull/15614

**Comment by p-i-** [comment]
Actually it's more fierce than that:
.venv/lib/python3.9/site-packages/nimporter.py autosets that flag (so in fact that .cfg file is redundant), so you have to comment it out:
```
    NIM_CLI_ARGS = [
        '--opt:speed',
        '--parallelBuild:0',
        '--gc:refc',
        '--threads:on',
        '--app:lib',
        '-d:release',
        '-d:strip',
        # '-d:lto',
        '-d:ssl'
    ] + (['--cc:vcc'] if 'MSC' in sys.version else [])
    EXT_DIR = 'nim-extensions'
```
If anyone can figure out how to do it without messing with `nimporter` please post up.

**Comment by p-i-** [comment]
In fact I can't see that that .cfg is used anywhere...

> I don't think there is an option to "disable all options". The best you can do is --skip<XXX>Cfg:on switches (Parent, Project etc), but it seems there is no --configFile:/path/

^ suggestion from nim gitter

**Comment by juancarlospaco** [comment]
@p-i- You seem interested, send Pull Request ?. :)

**Comment by p-i-** [comment]
I have to make a PR on nimporter first lol

**Comment by juancarlospaco** [comment]
> First step is to flag the issue to the nimporter maintainers... (done)

Nimporter is unmaintained, author does not have time anymore I think.

Nimporter needs a refactor, or maybe another solution from zero.

@SekouDiaoNlp was going to rewrite Nimporter, you are welcome to join the effort.

I am rewritting PIP itself, because is kinda dumb how it works,
it wont let you customize flags, params, locations, too much dependencies, slow, etc
you are welcome to join the effort, can be just testing/using it, or hacking into it,
it is for the most part working on Linux: https://github.com/juancarlospaco/plz#use

The fix of LTO should be done in Nim via Pull Request, 
and testing it on Mac to check is working.

I do not have a Mac.

Mac users can just git clone and compile.

Mac users can just use Docker, everyone uses Docker nowadays.

This package does not depend nor need Poetri, nowhere in doc says that.

**Comment by SekouDiaoNlp** [comment]
@juancarlospaco , sorry I am late to the discussion.

I fell sick with Covid and had to lay low for a while.

I am now back in shape, I think I should have time to implement a rewrite of nimporter by the end of the year if I have enough free time. At least enough to solve the current bugs.

Let me know if you are interested.

SekouDiaoNlp.

**Comment by SekouDiaoNlp** [comment]
Hi @juancarlospaco, @p-i-, @DavidGoedicke and @Nexuzzzz .

I just want to let you know that [nimporter v1.1.0](https://pypi.org/project/nimporter/) has just been released with a fix for this issue. See PR https://github.com/Pebaz/nimporter/pull/55 for more details.

Cheers
SekouDiaoNlp.

**Comment by Nexuzzzz** [comment]
nice!
