### ISSUE TITLE
Ubuntu 20.04 execution time error. 'faster_than_requests.nim.cfg'

### ISSUE THREAD

**Issue by IsraelLencina** [juancarlospaco/faster-than-requests#163]
- 32 Bit is not supported. **no**
- You must have 64 Bit Python 3. **checked**
- You must have 64 Bit GCC Compiler. **checked**
- You must have 64 Bit Operating System. **checked**
- Windows older than Windows 10 is not supported. **Ubuntu 20.04**
- ARM support is Experimental, you may need to compile manually. **no**
- Mac OSX support is Experimental, you may need to compile manually. **no**
- Alpine Linux support is Experimental, you may need to compile manually. **no**
- Termux support is Experimental, you may need to compile manually. **no**

Hi, i'm triying to use this library from Python 3.8.5 in Ubuntu 20.04. But when i do: `pip install faster-than-requests` and try to `import faster_than_requests as requests` that's the result:

```
Traceback (most recent call last):
  File "hilosPesados.py", line 4, in <module>
    import faster_than_requests as requests
  File "/home/israel/.local/lib/python3.8/site-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/usr/local/lib/python3.8/dist-packages/nimporter-1.0.4-py3.8.egg/nimporter.py", line 1150, in find_spec
  File "/usr/local/lib/python3.8/dist-packages/nimporter-1.0.4-py3.8.egg/nimporter.py", line 828, in import_nim_code
  File "/usr/local/lib/python3.8/dist-packages/nimporter-1.0.4-py3.8.egg/nimporter.py", line 588, in compile_nim_code
  File "/usr/local/lib/python3.8/dist-packages/nimporter-1.0.4-py3.8.egg/nimporter.py", line 56, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'faster_than_requests.nim.cfg'
```

**Comment by BiaChaudhry** [comment]
hey, I am having the same issue, any updates on this one, thanks!
system specs:
Ubuntu 20.04, Python 3.8.5, GCC  x86_64-Linux-gnu, Python 64 bit, system 64 bit.

**Comment by markgacoka** [comment]
Same issue on Ubuntu 20.04, Python 3.7, 64 bit system.

**Comment by VagnerBelfort** [comment]
I'm with the same problem, did anyone manage to solve it?

**Comment by ts-lang** [comment]
Tried to run `nim c -d:ssl -d:danger --app:lib --out:faster_than_requests.pyd faster_than_requests.nim`, it gives the following error,
`Error: invalid command line option: '--exceptions'`

**Comment by juancarlospaco** [comment]
We are working in fixing this in a new pull request
https://github.com/juancarlospaco/faster-than-requests/pull/183

**Comment by httplups** [comment]
Same error on Ubuntu
