### ISSUE TITLE
Support Python 3.9.2

### ISSUE THREAD

**Issue by machinexa2** [juancarlospaco/faster-than-requests#166]
Earlier versions could be imported (3.8) but this (3.9.2) gives error
```
root@kali:~/MachineYadav/My-Tools/URLCleaner# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
f>>> from faster_than_requests import head
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/usr/local/lib/python3.9/dist-packages/nimporter.py", line 1150, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "/usr/local/lib/python3.9/dist-packages/nimporter.py", line 828, in import_nim_code
    NimCompiler.compile_nim_code(
  File "/usr/local/lib/python3.9/dist-packages/nimporter.py", line 558, in compile_nim_code
    cls.ensure_nimpy()
  File "/usr/local/lib/python3.9/dist-packages/nimporter.py", line 270, in ensure_nimpy
    out, errors, _, _ = cls.invoke_compiler('nimble path nimpy'.split())
  File "/usr/local/lib/python3.9/dist-packages/nimporter.py", line 245, in invoke_compiler
    process = subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nimble'
>>> 
```

**Comment by machinexa2** [comment]
`apt install nim` fixes that however 
```
>>> from faster_than_requests import head
see it stuck
/root/.nimble/pkgs/nimpy-0.1.1/nimpy.nim(1051, 32) Warning: Cannot prove that 'arg0timeout' is initialized. This will become a compile time error in the future. [ProveInit]
```

**Comment by machinexa2** [comment]
However there's a warning

**Comment by juancarlospaco** [comment]
It is just a Warning, you can ignore it.

**Comment by reedniv** [comment]
not support to python 3.8

**Comment by juancarlospaco** [comment]
Python 3.8 is supported in the code.
