### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nimble'

### ISSUE THREAD

**Issue by muhammedattif** [juancarlospaco/faster-than-requests#173]
This error is raised when running the script for the first time

**Comment by cashcashcashcashcashcash** [comment]
Is there a fix?

**Comment by NaziYeeter** [comment]
Oof

**Comment by JulienDev** [comment]
Hello, did you find a solution?

**Comment by juancarlospaco** [comment]
is it Windows ?, did you reboot after install ?.

**Comment by MindMayhem** [comment]
> is it Windows ?, did you reboot after install ?.
> 
> Post the whole terminal output in a code block.

```
2021-09-24T19:46:47.304517+00:00   File "/app/main.py", line 3, in <module>
2021-09-24T19:46:47.304641+00:00     import faster_than_requests as requests
2021-09-24T19:46:47.304667+00:00   File "/app/.heroku/python/lib/python3.9/site-packages/faster_than_requests/__init__.py", line 7, in <module>
2021-09-24T19:46:47.304720+00:00     from . faster_than_requests import *
2021-09-24T19:46:47.304722+00:00   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-09-24T19:46:47.304801+00:00   File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
2021-09-24T19:46:47.304850+00:00   File "<frozen importlib._bootstrap>", line 925, in _find_spec
2021-09-24T19:46:47.304892+00:00   File "/app/.heroku/python/lib/python3.9/site-packages/nimporter.py", line 1150, in find_spec
2021-09-24T19:46:47.305211+00:00     return Nimporter.import_nim_code(fullname, path, library=False)
2021-09-24T19:46:47.305213+00:00   File "/app/.heroku/python/lib/python3.9/site-packages/nimporter.py", line 828, in import_nim_code
2021-09-24T19:46:47.305476+00:00     NimCompiler.compile_nim_code(
2021-09-24T19:46:47.305485+00:00   File "/app/.heroku/python/lib/python3.9/site-packages/nimporter.py", line 558, in compile_nim_code
2021-09-24T19:46:47.305663+00:00     cls.ensure_nimpy()
2021-09-24T19:46:47.305672+00:00   File "/app/.heroku/python/lib/python3.9/site-packages/nimporter.py", line 270, in ensure_nimpy
2021-09-24T19:46:47.305789+00:00     out, errors, _, _ = cls.invoke_compiler('nimble path nimpy'.split())
2021-09-24T19:46:47.305800+00:00   File "/app/.heroku/python/lib/python3.9/site-packages/nimporter.py", line 245, in invoke_compiler
2021-09-24T19:46:47.305899+00:00     process = subprocess.run(
2021-09-24T19:46:47.305908+00:00   File "/app/.heroku/python/lib/python3.9/subprocess.py", line 505, in run
2021-09-24T19:46:47.306068+00:00     with Popen(*popenargs, **kwargs) as process:
2021-09-24T19:46:47.306077+00:00   File "/app/.heroku/python/lib/python3.9/subprocess.py", line 951, in __init__
2021-09-24T19:46:47.306307+00:00     self._execute_child(args, executable, preexec_fn, close_fds,
2021-09-24T19:46:47.306316+00:00   File "/app/.heroku/python/lib/python3.9/subprocess.py", line 1821, in _execute_child
2021-09-24T19:46:47.306697+00:00     raise child_exception_type(errno_num, err_msg, err_filename)
2021-09-24T19:46:47.306720+00:00 FileNotFoundError: [Errno 2] No such file or directory: 'nimble'
```

**Comment by juancarlospaco** [comment]
is this a Mac OS ?.

**Comment by MindMayhem** [comment]
No, heroku BaaS, but seems like error appears and on Windows 10 too

пт, 24 сент. 2021 г., 22:57 Juan Carlos ***@***.***>:

**Comment by parucker** [comment]
This same error also appears on Ubuntu 20.04

**Comment by 2-X** [comment]
Same error on Ubuntu 20.04 on WSL2

**Comment by juancarlospaco** [comment]
So basically this is a Nimporter error.

Nimporter is a lib to make installation easy, created by someone else, not me,
then pull requested into this project,
then it broke, then that person leaves.

So basically if you Git clone and compile it works.
Or you can wait until I have time to fix it.

**Comment by rclough** [comment]
Confirming this issue on mac, steps to reproduce, in an isolted pyenv virtualenv with python 3.9:

```
pip install faster-than-requests
python
>> import faster_than_requests as requests
```

This triggers the error above. After installing nim via brew (`brew install nim`), I get a different error:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/p7/7ngjf1hx0dz9_jly5w_h_vtc0000gn/T/ipykernel_17036/2164804268.py in <module>
----> 1 import faster_than_requests as requests

~/.pyenv/versions/3.9.7/envs/fpp-flask/lib/python3.9/site-packages/faster_than_requests/__init__.py in <module>
      5 import nimporter
      6 
----> 7 from . faster_than_requests import *

~/.pyenv/versions/3.9.7/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

~/.pyenv/versions/3.9.7/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/.pyenv/versions/3.9.7/lib/python3.9/importlib/_bootstrap.py in _find_spec(name, path, target)

~/.pyenv/versions/3.9.7/envs/fpp-flask/lib/python3.9/site-packages/nimporter.py in find_spec(cls, fullname, path, target)
   1148     @classmethod
   1149     def find_spec(cls, fullname, path=None, target=None):
-> 1150         return Nimporter.import_nim_code(fullname, path, library=False)
   1151 
   1152 

~/.pyenv/versions/3.9.7/envs/fpp-flask/lib/python3.9/site-packages/nimporter.py in import_nim_code(cls, fullname, path, library)
    826 
    827             if cls.should_compile(module_path):
--> 828                 NimCompiler.compile_nim_code(
    829                     module_path.parent if library else module_path,
    830                     build_artifact,

~/.pyenv/versions/3.9.7/envs/fpp-flask/lib/python3.9/site-packages/nimporter.py in compile_nim_code(cls, module_path, build_artifact, library)
    586                 raise NimInvokeException(tmp_cwd, nim_args, errors, output)
    587             else:
--> 588                 raise NimCompileException(errors[0])
    589 
    590         for warn in warnings: print(warn)

~/.pyenv/versions/3.9.7/envs/fpp-flask/lib/python3.9/site-packages/nimporter.py in __init__(self, msg)
     46         else:
     47             nim_module, error_msg = msg.split('Error:')
---> 48             nim_module = nim_module.splitlines()[-1]
     49             mod, (line_col) = nim_module.split('(')
     50             nim_module = Path(mod)

IndexError: list index out of range
```

Not really sure where to go from here, since it's an error thrown while trying to report the real error :/

**Comment by KingWaffleIII** [comment]
So what is the temporary fix exactly?

**Comment by Fuhrer1939** [comment]
> Oof

hi i am also a nazi lover this is my watsapp number +91 8595740265 contact me asap from india.
Heil hitler

**Comment by tiger360** [comment]
Hey, any news with python 3.9.5  / Ubuntu 20.4 WSL ?
otherwise, what's the steps to compile it after cloning the repo ?
Thanks

**Comment by jerrychong25** [comment]
> Ubuntu 20.4 WSL

Same issue, unable to run Ubuntu 20.4 WSL here. Waiting for a solution.

**Comment by BazhanovD** [comment]
Debian/Ubuntu

**Comment by juancarlospaco** [comment]
We are working in a new branch https://github.com/juancarlospaco/faster-than-requests/pull/183

**Comment by zeandrade** [comment]
env: ( venv python 3.8)
nim            1.0.6-1      amd64      
faster-than-requests==21.3.3
python 3.8 (Ubuntu 20.04)
-------------------------------------------------------------------------------------------------------
Hi, I have the same error without nim. With nim installed, this error changes to:

```
>>> import faster_than_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/*****/codes/py/ftr_env/lib/python3.8/site-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/home/*****/codes/py/ftr_env/lib/python3.8/site-packages/nimporter/nimporter.py", line 253, in <lambda>
    lambda fullname, path, _: nimport(fullname, path, library=False)
  File "/home/****/codes/py/ftr_env/lib/python3.8/site-packages/nimporter/nimporter.py", line 217, in nimport
    compile_extension_to_lib(ext)
  File "/home/***/codes/py/ftr_env/lib/python3.8/site-packages/nimporter/nimporter.py", line 87, in compile_extension_to_lib
    raise CompilationFailedException(stderr)
nimporter.lib.CompilationFailedException: Nim Compilation Failed. Rerun with NIMPORTER_INSTRUMENT for full Nim output: command line(1, 2) Error: invalid command line option: '--backend'

>>>
```

**Comment by SmartManoj** [comment]
`curl https://nim-lang.org/choosenim/init.sh -sSf | sh
`
will install latest nim

**Comment by Letme** [comment]
Far from stale issue. I just hit it, so still not fixed today. Maybe we should change the packaging?

**Comment by crypt0miester** [comment]
can confirm, issue is still there.

**Comment by Sxvxgee** [comment]
Still getting this issue on ubuntu 22.04

**Comment by Shreeyak** [comment]
I just faced this issue as well. 
`brew install nim` solved the issue for me, on macOS.

**Comment by WebShark025** [comment]
Any updates on this?

With nim installed the error will change to:

```nimporter.lib.CompilationFailedException: Nim Compilation Failed. Rerun with NIMPORTER_INSTRUMENT for full Nim output: command line(1, 2) Error: invalid command line option: '--backend'```

**Comment by Vildnex** [comment]
I have the same issue even after I've tried this:

> `curl https://nim-lang.org/choosenim/init.sh -sSf | sh ` will install latest nim 1.6.4
> 
> Then use latest nimporter from git `pip install git+https://github.com/Pebaz/nimporter`

My error:
```
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nimble'
```

**Versions:**

* faster_than_requests==21.3.3
* Nim Compiler Version 2.0.2 [Linux: amd64]
* nimble v0.14.2 compiled at 2023-12-15 01:05:41
* pip 24.0
* Python 3.12.1
