### ISSUE TITLE
I cant install it.

### ISSUE THREAD

**Issue by Godwhitelight** [juancarlospaco/faster-than-requests#189]
When i am trying to install it i am getting an error with pip.
I am using win 11, administrator commandline 

ERORR:

C:\Users\bargi>py -m pip install faster-than-requests
Collecting faster-than-requests
  Using cached faster_than_requests-21.03.03.zip (4.9 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\bargi\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bargi\\AppData\\Local\\Temp\\pip-install-547i29nw\\faster-than-requests_60dd6cb603e6439e958c64cc4b25cbef\\setup.py'"'"'; __file__='"'"'C:\\Users\\bargi\\AppData\\Local\\Temp\\pip-install-547i29nw\\faster-than-requests_60dd6cb603e6439e958c64cc4b25cbef\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\bargi\AppData\Local\Temp\pip-pip-egg-info-yhooykdn'
         cwd: C:\Users\bargi\AppData\Local\Temp\pip-install-547i29nw\faster-than-requests_60dd6cb603e6439e958c64cc4b25cbef\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\bargi\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bargi\\AppData\\Local\\Temp\\pip-wheel-o58c9j47\\choosenim-install_a967827e299941c590f5a1f524a2d007\\setup.py'"'"'; __file__='"'"'C:\\Users\\bargi\\AppData\\Local\\Temp\\pip-wheel-o58c9j47\\choosenim-install_a967827e299941c590f5a1f524a2d007\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\bargi\AppData\Local\Temp\pip-wheel-z6xvxzcy'
           cwd: C:\Users\bargi\AppData\Local\Temp\pip-wheel-o58c9j47\choosenim-install_a967827e299941c590f5a1f524a2d007\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for choosenim-install
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\bargi\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\bargi\\AppData\\Local\\Temp\\tmpxcrcl23h', '--quiet', 'choosenim_install']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bargi\AppData\Local\Temp\pip-install-547i29nw\faster-than-requests_60dd6cb603e6439e958c64cc4b25cbef\setup.py", line 2, in <module>
        setuptools.setup(package_data = {"": ["*.nim", "*.nims", "*.cfg", "*.dll", "*.so", "*.h", "*.hpp"]})
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 806, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
        return installer(requirement)
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 877, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\Users\bargi\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['C:\\Users\\bargi\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\bargi\\AppData\\Local\\Temp\\tmpxcrcl23h', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip#sha256=3cc247556e10c64d8897933304670c873236026b4ef9f219215b124e990c2dac (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faster-than-requests (from versions: 21.3.3)
ERROR: No matching distribution found for faster-than-requests
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\bargi\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

How can i manually install that?

**Comment by vellrya** [comment]
Same error, python 3.9.9 + win 10

**Comment by ggoaat** [comment]
Not compatible with windows?

**Comment by ilovedogs1235** [comment]
same error here too

**Comment by ilovedogs1235** [comment]
requires-python:>=3.6

**Comment by z6Solutions** [comment]
I've tested this on Windows 10 and Ubuntu 20.04, using Python 3.8.10 and 3.10.2 - it failed in both environments on both versions of Python. I already had Nim installed and working (as well as git) on both systems. The error is indicating that a wheel is missing during installation.

**Comment by SmartManoj** [comment]
https://stackoverflow.com/a/44862371

**Comment by juancarlospaco** [comment]
The code itself does not really depend on wheel,
but PIP maybe, but I can not fix PIP sorry.

The code itself does not really depend on Python `>3.6`,
but older than 3.6 is EOL by Python, but I can not fix Python itself sorry.

**Comment by themysticsavages** [comment]
Hmm... I see `error: invalid command 'bdist_wheel'`
Maybe try updating setuptools?

```
py -m pip install -U setuptools
```

**Comment by alimp5** [comment]
build failed on windows 10 - 64 bit.
python 3.8.10 - 64 bit.

pip install faster_than_requests

```
Collecting faster_than_requests
  Using cached faster_than_requests-21.03.03.zip (4.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
        error: subprocess-exited-with-error
     
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [54 lines of output]
            running bdist_wheel
            running build
            f:\ea_snipe\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. 
              warnings.warn(
            installing to build\bdist.win-amd64\wheel
            running install
            running install_egg_info
            running egg_info
            writing choosenim_install.egg-info\PKG-INFO
            writing dependency_links to choosenim_install.egg-info\dependency_links.txt
            deleting choosenim_install.egg-info\requires.txt
            writing top-level names to choosenim_install.egg-info\top_level.txt
            writing manifest file 'choosenim_install.egg-info\SOURCES.txt'
            reading manifest file 'choosenim_install.egg-info\SOURCES.txt'
            writing manifest file 'choosenim_install.egg-info\SOURCES.txt'
            Copying choosenim_install.egg-info to build\bdist.win-amd64\wheel\.\choosenim_install-0.5.5-py3.8.egg-info
            running install_scripts
            choosenim v0.6.0 (2020-03-06 18:45:17) [windows/amd64]
            C:\Users\linux-11\AppData\Local\Temp\pip-wheel-dh31wtd7\choosenim-install_a0ec32356bfd4620a0308c75690bc31f\setup.py:86: UserWarning: Choosenim is already installed and working on the system choosenim.exe
              warnings.warn("Choosenim is already installed and working on the system " + choosenim_exe)
               Updating choosenim
            C:\Users\linux-11\AppData\Local\Temp\pip-wheel-dh31wtd7\choosenim-install_a0ec32356bfd4620a0308c75690bc31f\setup.py:88: UserWarning: Failed to run 'choosenim.exe update self'   
              warnings.warn("Failed to run '" + choosenim_exe + " update self'")  # Dont worry if "update self" fails.
               Updating stable
            C:\Users\linux-11\AppData\Local\Temp\pip-wheel-dh31wtd7\choosenim-install_a0ec32356bfd4620a0308c75690bc31f\setup.py:92: UserWarning: Failed to run 'choosenim.exe update stable' 
              warnings.warn("Failed to run '" + choosenim_exe + " update stable'")
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "C:\Users\linux-11\AppData\Local\Temp\pip-wheel-dh31wtd7\choosenim-install_a0ec32356bfd4620a0308c75690bc31f\setup.py", line 210, in <module>
                setuptools.setup(
              File "f:\ea_snipe\lib\site-packages\setuptools\__init__.py", line 87, in setup
                return distutils.core.setup(**attrs)
              File "f:\ea_snipe\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
                return run_commands(dist)
              File "f:\ea_snipe\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
                dist.run_commands()
              File "f:\ea_snipe\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
                self.run_command(cmd)
              File "f:\ea_snipe\lib\site-packages\setuptools\dist.py", line 1229, in run_command
                super().run_command(command)
              File "f:\ea_snipe\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
                cmd_obj.run()
              File "f:\ea_snipe\lib\site-packages\wheel\bdist_wheel.py", line 335, in run
                self.run_command('install')
              File "f:\ea_snipe\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
                self.distribution.run_command(command)
              File "f:\ea_snipe\lib\site-packages\setuptools\dist.py", line 1229, in run_command
                super().run_command(command)
              File "f:\ea_snipe\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
                cmd_obj.run()
              File "C:\Users\linux-11\AppData\Local\Temp\pip-wheel-dh31wtd7\choosenim-install_a0ec32356bfd4620a0308c75690bc31f\setup.py", line 208, in run
                raise Exception(IOError, "Failed to install choosenim")
            Exception: (<class 'OSError'>, 'Failed to install choosenim')
            [end of output]
     
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for choosenim_install
      ERROR: Failed to build one or more wheels
      f:\ea_snipe\lib\site-packages\setuptools\config\setupcfg.py:459: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      f:\ea_snipe\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.   
        warnings.warn(
      Traceback (most recent call last):
        File "f:\ea_snipe\lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "C:\Python38\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['f:\\ea_snipe\\scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\linux-11\\AppData\\Local\\Temp\\tmpsu4mpba3', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\linux-11\AppData\Local\Temp\pip-install-9zgu1f4d\faster-than-requests_47e8cf6b2cfc49eab9901efab0b41fd1\setup.py", line 2, in <module>
          setuptools.setup(package_data = {"": ["*.nim", "*.nims", "*.cfg", "*.dll", "*.so", "*.h", "*.hpp"]})
        File "f:\ea_snipe\lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "f:\ea_snipe\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "f:\ea_snipe\lib\site-packages\setuptools\dist.py", line 876, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "f:\ea_snipe\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "f:\ea_snipe\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "f:\ea_snipe\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
        File "f:\ea_snipe\lib\site-packages\setuptools\dist.py", line 956, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "f:\ea_snipe\lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['f:\\ea_snipe\\scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\linux-11\\AppData\\Local\\Temp\\tmpsu4mpba3', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by 21oramaster** [comment]
Same here:
Windows 10
Python 3.10.1
pip 22.1

**Comment by BernardoOlisan** [comment]
guys, 2022, you have to solve this

**Comment by BernardoOlisan** [comment]
solved it, try installing first `pip install wheel`
hope it helps
