### ISSUE TITLE
After installing this package manual. 

### ISSUE THREAD

**Issue by znel2002** [juancarlospaco/faster-than-requests#191]
### Architecture

x86_64 (Default)

### Operating System

Windows

### Disk

HDD (SATA, IDE, Mechanical)

### Memory

8 Gigabytes

### CPU Cores

Others (Unkown)

### Internet Connection

Wifi (WLAN, Wireless)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

Germany

### What happened?

Code:
`import faster_than_requests as requests`

Error: 
`Traceback (most recent call last):
  File "C:\Users\Kim Harre\PycharmProjects\Nuker\Zynixx\main.py", line 2, in <module>
    from faster_than_requests import faster_than_requests as requests
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\faster_than_requests\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\nimporter.py", line 253, in <lambda>
    lambda fullname, path, _: nimport(fullname, path, library=False)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\nimporter.py", line 214, in nimport
    ext = ExtLib(module_path, Path(), library)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\lib.py", line 316, in __init__
    self.import_namespace = get_import_path(self.relative_path, root)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\lib.py", line 111, in get_import_path
    import_prefix = get_import_prefix(module_path.parent, root)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\lib.py", line 104, in get_import_prefix
    assert full_path >= root_path, 'Extension path is not within root dir.'
AssertionError: Extension path is not within root dir.`

As i said it was manual installed, because pip didn't work.
Thanks

### Standard Output Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Kim Harre\PycharmProjects\Nuker\Zynixx\main.py", line 2, in <module>
    from faster_than_requests import faster_than_requests as requests
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\faster_than_requests\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\nimporter.py", line 253, in <lambda>
    lambda fullname, path, _: nimport(fullname, path, library=False)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\nimporter.py", line 214, in nimport
    ext = ExtLib(module_path, Path(), library)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\lib.py", line 316, in __init__
    self.import_namespace = get_import_path(self.relative_path, root)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\lib.py", line 111, in get_import_path
    import_prefix = get_import_prefix(module_path.parent, root)
  File "C:\Users\Kim Harre\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter\lib.py", line 104, in get_import_prefix
    assert full_path >= root_path, 'Extension path is not within root dir.'
AssertionError: Extension path is not within root dir.
```
![image](https://user-images.githubusercontent.com/99537307/163170089-f730e67f-7a4f-457c-abf4-8c90f9300ce0.png)

**Comment by ahmetveburak** [comment]
How did you resolve it?

**Comment by znel2002** [comment]
Sadly i havn't. I just used an alternative.

**Comment by Hmiku8338** [comment]
Manjaro Linux Xfce here. Python 3.8 through poetry -- same issue.
