### ISSUE TITLE
[bug] Nim Compilation Failed. invalid command line option: '--backend'

### ISSUE THREAD

**Issue by chriseomi** [juancarlospaco/faster-than-requests#196]
### Architecture

x86_64 (Default)

### Operating System

Linux

### Disk

SSD (Solid)

### Memory

256 Gigabytes

### CPU Cores

16 CPU Cores

### Internet Connection

LAN (RJ45, Local, etc)

### What is your web browser?

Firefox/Firefox Fork

### Device

Server PC

### Where are you from?

United States

### What happened?

Step. Fresh install Ubuntu 20.0.4

1. `sudo apt install python3-pip`
2. `pip install faster_than_requests`
3. `sudo apt install nim`
4. `python3 example2.py` (from the repo \examples folder)

### Standard Output Logs

```shell
ubuntu@ftr:~$ python3 example2.py
Traceback (most recent call last):
  File "example2.py", line 3, in <module>
    import faster_than_requests as reqs
  File "/home/ubuntu/.local/lib/python3.8/site-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nimporter/nimporter.py", line 253, in <lambda>
    lambda fullname, path, _: nimport(fullname, path, library=False)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nimporter/nimporter.py", line 217, in nimport
    compile_extension_to_lib(ext)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nimporter/nimporter.py", line 87, in compile_extension_to_lib
    raise CompilationFailedException(stderr)
nimporter.lib.CompilationFailedException: Nim Compilation Failed. Rerun with NIMPORTER_INSTRUMENT for full Nim output: command line(1, 2) Error: invalid command line option: '--backend'
```

**Comment by mcode11** [comment]
Hey!
use https://pypi.org/project/nim-install/

**Comment by mcode11** [comment]
@chriseomi
