### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Arthavruksha** [juancarlospaco/faster-than-requests#198]
### Architecture

x86_64 (Default)

### Operating System

Windows

### Disk

Others (USB)

### Memory

8 Gigabytes

### CPU Cores

1 CPU Cores

### Internet Connection

Wifi (WLAN, Wireless)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

India

### What happened?

This error is coming raised when running the python file for the first time after installation of faster-than-requests in Windows via Pip

### Standard Output Logs

```shell
Traceback (most recent call last):
  File "c:\Shodh by Arthavruksha\Realtime\pdftotext.py", line 1, in <module>
    from faster_than_requests import requests
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 944, in import_nim_code
    NimCompiler.compile_nim_code(
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 696, in compile_nim_code
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 294, in ensure_nimpy
    out, errors, _, _ = cls.invoke_compiler('nimble path nimpy'.split())
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 269, in invoke_compiler
    process = subprocess.run(
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
PS C:\Shodh by Arthavruksha\Realtime> python -u "c:\Shodh by Arthavruksha\Realtime\pdftotext.py"
Traceback (most recent call last):
  File "c:\Shodh by Arthavruksha\Realtime\pdftotext.py", line 1, in <module>
    from faster_than_requests import requests
ModuleNotFoundError: No module named 'faster_than_requests'
PS C:\Shodh by Arthavruksha\Realtime> pip install faster-than-requests
Collecting faster-than-requests
  Using cached faster_than_requests-21.3.3-py3-none-any.whl
Requirement already satisfied: nimporter in c:\users\shweta\appdata\local\programs\python\python310\lib\site-packages (from faster-than-requests) (1.1.0)
Installing collected packages: faster-than-requests
Successfully installed faster-than-requests-21.3.3
PS C:\Shodh by Arthavruksha\Realtime> python -u "c:\Shodh by Arthavruksha\Realtime\pdftotext.py"
Traceback (most recent call last):
  File "c:\Shodh by Arthavruksha\Realtime\pdftotext.py", line 1, in <module>
    from faster_than_requests import requests
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 944, in import_nim_code
    NimCompiler.compile_nim_code(
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 696, in compile_nim_code
    cls.ensure_nimpy()
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 294, in ensure_nimpy
    out, errors, _, _ = cls.invoke_compiler('nimble path nimpy'.split())
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 269, in invoke_compiler
    process = subprocess.run(
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\shweta\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by ShodhArthavruksha** [comment]
Facing same issue . If anyone knows do help to solve it

**Comment by asdcxfrt** [comment]
I installed NIM. Reinstalled this library. Rebooted the computer. And this error disappeared.
