### ISSUE TITLE
Can't locate my nim installation on EC2 Server [bug] 

### ISSUE THREAD

**Issue by wrc-wise** [juancarlospaco/faster-than-requests#205]
### Architecture

x86_64 (Default)

### Operating System

Linux

### Disk

NVME (M2, MSATA)

### Memory

8 Gigabytes

### CPU Cores

4 CPU Cores

### Internet Connection

Optical Fiber (very fast)

### What is your web browser?

Others (Unkown)

### Device

VirtualBox/Vagrant (Virtual Machine)

### Where are you from?

United Kingdom

### What happened?

Nim installed via these instructions on my EC2 instance: https://nim-lang.org/install_unix.html

FTR installs no problems on the server but running the code results in the error included below, seemingly due to the module not being able to locate my nim installation.

For the sake of inclusion, I've also included output from installing nim here:

```(vc) ubuntu@ip-XXXXXX:~$ curl https://nim-lang.org/choosenim/init.sh -sSf | sh
choosenim-init: Downloading choosenim-0.8.4_linux_amd64
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: n
      Info: Version 1.6.8 already selected
choosenim-init: ChooseNim installed in /home/ubuntu/.nimble/bin
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.
choosenim-init: Place the following line in the ~/.profile or ~/.bashrc file.
choosenim-init:     export PATH=/home/ubuntu/.nimble/bin:$PATH```

### Standard Output Logs

```shell
(vc) ubuntu@ip-XXXXXXX:~$ python3 XXXXXX/XXXXXXX/XXXXXX.py 
Traceback (most recent call last):
  File "/home/ubuntu/XXXXXXXXX.py", line 9, in <module>
    import faster_than_requests as ftr
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/site-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/site-packages/nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/site-packages/nimporter.py", line 944, in import_nim_code
    NimCompiler.compile_nim_code(
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/site-packages/nimporter.py", line 696, in compile_nim_code
    cls.ensure_nimpy()
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/site-packages/nimporter.py", line 294, in ensure_nimpy
    out, errors, _, _ = cls.invoke_compiler('nimble path nimpy'.split())
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/site-packages/nimporter.py", line 269, in invoke_compiler
    process = subprocess.run(
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/anaconda3/envs/vc/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nimble'
```

**Comment by juancarlospaco** [comment]
We are not devs of Nimble nor Choosenim, please see documentation of each project.

The solution is there, you have to add it to `PATH` and restart the shells.
