### ISSUE TITLE
[Errno 2] No such file or directory: 'nimble'

### ISSUE THREAD

**Issue by lwinkelm** [juancarlospaco/faster-than-requests#206]
### Architecture

x86_64 (Default)

### Operating System

Linux

### Disk

SSD (Solid)

### Memory

16 Gigabytes

### CPU Cores

8 CPU Cores

### Internet Connection

Wifi (WLAN, Wireless)

### What is your web browser?

Firefox/Firefox Fork

### Device

Desktop PC

### Where are you from?

France

### What happened?

Using conda envs

![image](https://user-images.githubusercontent.com/82231168/197015485-970423fe-5f8f-4fdb-8f83-25e78335c2f4.png)

When I try to:
 import faster_than_requests as request

I get the following error:

[Errno 2] No such file or directory: 'nimble'

**Comment by sym-p1337** [comment]
Same issue, running Pop!_OS
Uname output: Linux pop-os 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux
Python version: Python 3.10.6

**Comment by scripthon** [comment]
same issue, on debian 11

```shell
coder@railway:~/project$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faster_than_requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/coder/.local/lib/python3.9/site-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/home/coder/.local/lib/python3.9/site-packages/nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "/home/coder/.local/lib/python3.9/site-packages/nimporter.py", line 944, in import_nim_code
    NimCompiler.compile_nim_code(
  File "/home/coder/.local/lib/python3.9/site-packages/nimporter.py", line 696, in compile_nim_code
    cls.ensure_nimpy()
  File "/home/coder/.local/lib/python3.9/site-packages/nimporter.py", line 294, in ensure_nimpy
    out, errors, _, _ = cls.invoke_compiler('nimble path nimpy'.split())
  File "/home/coder/.local/lib/python3.9/site-packages/nimporter.py", line 269, in invoke_compiler
    process = subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nimble'
>>> 
```

**Comment by bibi21000** [comment]
hi
Seem you need to install nim programming language : https://nim-lang.org/install.html
hth
