### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by ingjavierpinilla** [juancarlospaco/faster-than-requests#225]
### Architecture

x86_64 (Default)

### Operating System

Linux

### Disk

SSD (Solid)

### Memory

2 Gigabytes

### CPU Cores

2 CPU Cores

### Internet Connection

Optical Fiber (very fast)

### What is your web browser?

Chrome/Chromium

### Device

VirtualBox/Vagrant (Virtual Machine)

### Where are you from?

Colombia

### What happened?

On a vm I got that error message

here is some other information

pip 24.0 from /home/ec2-user/test/venv/lib64/python3.9/site-packages/pip (python 3.9)
Python 3.9.16
Nim Compiler Version 2.0.0 [Linux: amd64]

[this](https://stackoverflow.com/questions/78058395/how-to-fix-this-error-simple-run-error-with-the-library-faster-than-requests) seems related to the issue 

### Standard Output Logs

```shell
Traceback (most recent call last):
  File "/home/ec2-user/test/main.py", line 7, in <module>
    import faster_than_requests as requests
  File "/home/ec2-user/test/venv/lib64/python3.9/site-packages/faster_than_requests/__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/home/ec2-user/test/venv/lib64/python3.9/site-packages/nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "/home/ec2-user/test/venv/lib64/python3.9/site-packages/nimporter.py", line 944, in import_nim_code
    NimCompiler.compile_nim_code(
  File "/home/ec2-user/test/venv/lib64/python3.9/site-packages/nimporter.py", line 705, in compile_nim_code
    cls.check_compile_errors(errors, library, nim_args, output, tmp_cwd, warnings)
  File "/home/ec2-user/test/venv/lib64/python3.9/site-packages/nimporter.py", line 492, in check_compile_errors
    raise NimCompileException(errors[0])
nimporter.NimCompileException: faster_than_requests.nim(2, 18) Error: cannot open file: db_sqlite
```

**Comment by ingjavierpinilla** [comment]
I installed nim 1.6.18 and got this output

`std/db_sqlite(184, 1) Warning: Circular dependency detected. `codeReordering` pragma may not be able to reorder some nodes properly [User]
ws.nim(306, 6) Warning: target type is larger than source type [CastSizes]
ws.nim(329, 32) Warning: conversion to enum with holes is unsafe: Opcode(b0 and 0x0000000F) [HoleEnumConv]
nimpy.nim(562, 32) Warning: Cannot prove that 'arg0timeout' is initialized. This will become a compile time error in the future. [ProveInit]
faster_than_requests.nim(293, 132) Warning: Deprecated since v1.5; Use auto instead.; any is deprecated [Deprecated]
faster_than_requests.nim(298, 101) Warning: Deprecated since v1.5; Use auto instead.; any is deprecated [Deprecated]
could not load: libpcre.so(.3|.1|)
(compile with -d:nimDebugDlOpen for more information)`

**Comment by umarbutler** [comment]
+1
