### ISSUE TITLE
[bug] (<class 'OSError'>, 'Failed to install choosenim')

### ISSUE THREAD

**Issue by MuneebAhmedQureshi** [juancarlospaco/faster-than-requests#226]
### Architecture

x86_64 (Default)

### Operating System

Windows

### Disk

SSD (Solid)

### Memory

8 Gigabytes

### CPU Cores

4 CPU Cores

### Internet Connection

Optical Fiber (very fast)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

Pakistan

### What happened?

When I tried installing library using py -m pip install faster-than-requests the following dependency error occurred. 

### Standard Output Logs

```shell
Collecting faster-than-requests
  Using cached faster_than_requests-21.03.03.zip (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      Collecting choosenim_install
        Using cached choosenim_install-0.5.5.zip (9.7 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: choosenim_install
        Building wheel for choosenim_install (pyproject.toml): started
        Building wheel for choosenim_install (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        Building wheel for choosenim_install (pyproject.toml) did not run successfully.
        exit code: 1
      
        [62 lines of output]
        running bdist_wheel
        running build
        installing to build\bdist.win-amd64\wheel
        running install
        running install_egg_info
        running egg_info
        writing choosenim_install.egg-info\PKG-INFO
        writing dependency_links to choosenim_install.egg-info\dependency_links.txt
        writing top-level names to choosenim_install.egg-info\top_level.txt
        reading manifest file 'choosenim_install.egg-info\SOURCES.txt'
        writing manifest file 'choosenim_install.egg-info\SOURCES.txt'
        Copying choosenim_install.egg-info to build\bdist.win-amd64\wheel\.\choosenim_install-0.5.5-py3.12.egg-info
        running install_scripts
        choosenim v0.6.0 (2020-03-06 18:45:17) [windows/amd64]
        <string>:86: UserWarning: Choosenim is already installed and working on the system choosenim.exe
           Updating choosenim
        <string>:88: UserWarning: Failed to run 'choosenim.exe update self'
           Updating stable
        <string>:92: UserWarning: Failed to run 'choosenim.exe update stable'
        Traceback (most recent call last):
          File "C:\Users\PMYLS\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\Users\PMYLS\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\PMYLS\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
            return _build_backend().build_wheel(wheel_directory, config_settings,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\build_meta.py", line 415, in build_wheel
            return self._build_with_temp_dir(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
            self.run_setup()
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
            super().run_setup(setup_script=setup_script)
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
            exec(code, locals())
          File "<string>", line 210, in <module>
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup      
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
            dist.run_commands()
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 970, in run_commands
            self.run_command(cmd)
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\dist.py", line 974, in run_command    
            super().run_command(command)
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
            cmd_obj.run()
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 408, in run
            self.run_command("install")
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
            self.distribution.run_command(command)
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\dist.py", line 974, in run_command    
            super().run_command(command)
          File "C:\Users\PMYLS\AppData\Local\Temp\pip-build-env-2bjjtgz8\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 989, in run_command
            cmd_obj.run()
          File "<string>", line 208, in run
        Exception: (<class 'OSError'>, 'Failed to install choosenim')
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for choosenim_install
      Failed to build choosenim_install
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (choosenim_install)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by umarbutler** [comment]
+1

**Comment by tima1906** [comment]
+1
