### ISSUE TITLE
Failed installation with pip3

### ISSUE THREAD

**Issue by TimurNurlygayanov** [juancarlospaco/faster-than-requests#58]
**Bug**
I can't install faster-than-requests library with pip3 on MacOS.

**To Reproduce**
1) Run on MacOS: pip3 install faster_than_requests

**Expected behavior**
The package should be installed without errors.

**Actual Behaviour:**
There is an error during the installation:
```
 pip3 install faster_than_requests
Collecting faster_than_requests
  Downloading faster_than_requests-0.9.8.zip (435 kB)
     |████████████████████████████████| 435 kB 400 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6q/0l3xkvl518537f8003rtx55c0000gn/T/pip-install-lwq5te7j/faster-than-requests/setup.py'"'"'; __file__='"'"'/private/var/folders/6q/0l3xkvl518537f8003rtx55c0000gn/T/pip-install-lwq5te7j/faster-than-requests/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6q/0l3xkvl518537f8003rtx55c0000gn/T/pip-install-lwq5te7j/faster-than-requests/pip-egg-info
         cwd: /private/var/folders/6q/0l3xkvl518537f8003rtx55c0000gn/T/pip-install-lwq5te7j/faster-than-requests/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/usr/local/lib/python3.7/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/usr/local/lib/python3.7/site-packages/pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Desktop (please complete the following information):**
 - OS: Darwin MacBookPro-TNurlygaianov 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
- PIP: pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by juancarlospaco** [comment]
Hello, thanks for a complete bug report, nicely written.

So basically I dont own a Mac (unless someone donate a Mac to me) :P
I have no way to better check and play with the code on Mac for a better experience.

But you can just use the source code, Git clone and Compile, 
the GitHub Actions CI build every commit from zero with very basic commands (curl, etc),
also the Windows section explains how to do it too https://github.com/juancarlospaco/faster-than-requests#windows
also a lot of people just use Docker nowadays.
