### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by chalist** [juancarlospaco/faster-than-requests#99]
When I try to install app, I got this error:

```bash
$ pip install faster-than-requests -vvv
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-n2991ybc
Created temporary directory: /tmp/pip-req-tracker-ghc7ij5k
Initialized build tracking at /tmp/pip-req-tracker-ghc7ij5k
Created build tracker: /tmp/pip-req-tracker-ghc7ij5k
Entered build tracker: /tmp/pip-req-tracker-ghc7ij5k
Created temporary directory: /tmp/pip-install-f31wwwj1
1 location(s) to search for versions of faster-than-requests:
* https://pypi.org/simple/faster-than-requests/
Fetching project page and analyzing links: https://pypi.org/simple/faster-than-requests/
Getting page https://pypi.org/simple/faster-than-requests/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/faster-than-requests/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/faster-than-requests/ HTTP/1.1" 304 0
  Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/aa/e3/d3018380bfb1415a1a951fb64ad728b74ef985ba5be5f43648599c3a91bb/faster_than_requests-49d49f0.zip#sha256=3054b89557bbbec8d22b669943f898b5ef71d7c11f287d9e9b71a45b7aaeee7b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
  Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/19/85/00e7ffcb14c8a9c7f5b366e21e0da6252b05dc80521231df08586dfdeb8d/faster_than_requests-d4d03a6.zip#sha256=30defae729a4b0a67bd986a0cd0898d943a347a2e3e45759e7b9facb02051679 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
  Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/55/32/d77019eac8980d71c96ebbd266f324e753d75815e88414bad431c1a7f69d/faster_than_requests-57c7862.zip#sha256=e9d08cd824ced57b940eb3fec2b3b1c221de86efe5fc575b6b495c283c80116b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
  Link requires a different Python (3.6.9 not in: '>=3.8'): https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8)
Given no hashes to check 0 links for project 'faster-than-requests': discarding no candidates
ERROR: Could not find a version that satisfies the requirement faster-than-requests (from versions: none)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-ghc7ij5k'
ERROR: No matching distribution found for faster-than-requests
Exception information:
Traceback (most recent call last):
  File "/var/lib/app/.virtualenvs/app/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/var/lib/app/.virtualenvs/app/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/var/lib/app/.virtualenvs/app/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/var/lib/app/.virtualenvs/app/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/lib/app/.virtualenvs/app/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/var/lib/app/.virtualenvs/app/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/var/lib/app/.virtualenvs/app/lib/python3.6/site-packages/pip/_internal/index/package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for faster-than-requests
WARNING: You are using pip version 20.0.2; however, version 20.2.4 is available.
You should consider upgrading via the '/var/lib/app/.virtualenvs/app/bin/python -m pip install --upgrade pip' command.
```

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

How can I fix this issue?
Thanks.

**Comment by juancarlospaco** [comment]
`sudo pip3 install faster-than-requests==57c7862 --no-binary :all: `

**Comment by chalist** [comment]
Thanks for quick answer.
I get error again:

```
pip3 install faster-than-requests==57c7862 --no-binary :all:
ERROR: Could not find a version that satisfies the requirement faster-than-requests==57c7862 (from versions: none)
ERROR: No matching distribution found for faster-than-requests==57c7862
```

**Comment by juancarlospaco** [comment]
Check that:
- OS is 64 Bit.
- Python is 64 Bit.
- Python is `3.8.0` or newer.
- PIP is `20.2.4` or newer.

**Comment by chalist** [comment]
1:
```bash
$ file /lib/systemd/systemd
/lib/systemd/systemd: ELF 64-bit LSB shared object...
```

2 & 3.
```
$ python
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('64bit', 'ELF')
>>> 
```
4.
```bash
$ pip --version
pip 20.2.4 from /var/lib/...
```

**Comment by juancarlospaco** [comment]
![temp](https://user-images.githubusercontent.com/1189414/96590625-9fdacb80-12bc-11eb-8104-3d248ea52af3.png)

**Comment by juancarlospaco** [comment]
`/var/lib/app/.virtualenvs/app/lib/python3.6/` on your traceback messages,
it seems something somehow is trying to install the package on a virtualenv with Python 3.6.0 and that will not work,
seems like your computer is misconfigured or something, looks like a problem on your end.

**Comment by chalist** [comment]
Sorry that traceback message was for before python upgrage.

I upgrade python and try again, but got same error:

```bash
1 location(s) to search for versions of faster-than-requests:
* https://pypi.org/simple/faster-than-requests/
Fetching project page and analyzing links: https://pypi.org/simple/faster-than-requests/
Getting page https://pypi.org/simple/faster-than-requests/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/faster-than-requests/" in the cache
Request header has "max_age" as 0, cache bypassed
https://pypi.org:443 "GET /simple/faster-than-requests/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/aa/e3/d3018380bfb1415a1a951fb64ad728b74ef985ba5be5f43648599c3a91bb/faster_than_requests-49d49f0.zip#sha256=3054b89557bbbec8d22b669943f898b5ef71d7c11f287d9e9b71a45b7aaeee7b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8), version: 49d49f0
  Found link https://files.pythonhosted.org/packages/19/85/00e7ffcb14c8a9c7f5b366e21e0da6252b05dc80521231df08586dfdeb8d/faster_than_requests-d4d03a6.zip#sha256=30defae729a4b0a67bd986a0cd0898d943a347a2e3e45759e7b9facb02051679 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8), version: d4d03a6
  Found link https://files.pythonhosted.org/packages/55/32/d77019eac8980d71c96ebbd266f324e753d75815e88414bad431c1a7f69d/faster_than_requests-57c7862.zip#sha256=e9d08cd824ced57b940eb3fec2b3b1c221de86efe5fc575b6b495c283c80116b (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8), version: 57c7862
  Found link https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.8), version: 3572925
Given no hashes to check 0 links for project 'faster-than-requests': discarding no candidates
ERROR: Could not find a version that satisfies the requirement faster-than-requests==0.9.6 (from -r requirements.txt (line 27)) (from versions: d4d03a6, 49d49f0, 57rc7862, 3572925)
ERROR: No matching distribution found for faster-than-requests==0.9.6 (from -r requirements.txt (line 27))
Exception information:
Traceback (most recent call last):
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/var/lib/app/.virtualenvs/app/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 928, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for faster-than-requests==0.9.6 (from -r requirements.txt (line 27))
Removed build tracker: '/tmp/pip-req-tracker-1yv9tgk8'


```

**Comment by juancarlospaco** [comment]
Try with `pip3 install faster-than-requests==57c7862 --no-binary :all: ` and post the whole traceback.

**Comment by chalist** [comment]
I think python version was my mistake. After upgrade to 3.8, `pip3 install faster-than-requests==3572925 --no-binary :all: ` works fine.
Problem solved.
Thanks
